### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by DrPintoThe2nd** [beiko-lab/RADProc#1]
Hi,

I am trying to download the program an have two issues before I get started:
Instructions provided: 
"In the Terminal:
• Traverse to the folder "Install".
$ ./configure"

(1) There is no "Install" folder that I can see.
(2) ./configure (when run from the 'home' RADProc folder) provides a permission denied error, even when run as the super user.

Thanks for your work on this! Looking forward to using it!
Best,
bjp

**Comment by praveennr** [comment]
Hi,

Thanks for bringing this to my attention!
Please download the software again and follow these instructions

Traverse to "Install" folder ( Sorry I missed to rename the folder earlier)

$autoreconf --install
$sh ./configure   (use sh if you face the permission denied issue)
$ make
root access or sudo
$ make install

Hope this helps! Please let me know if you face any issues.

Regards,
Praveen

**Comment by DrPintoThe2nd** [comment]
Seems to have worked perfectly! Thanks!

Cheers,
bjp
