### ISSUE TITLE
RADProc consistently throws 'Segmentation error' during processing...

### ISSUE THREAD

**Issue by Vierod** [beiko-lab/RADProc#3]
Hi,

Trying to get RADProc working on an Ubuntu system (have tried on a 16.04 machine, 18.10, and on google's colab server) and with GCC 4/5/6/7/8.

Consistently getting the same issue -

 Parameter sweep mode: off
 Maximum distance (in nucleotides) allowed between stacks to form network: 4
 Minimum coverage depth: 3
 Maximum number stacks per locus: 3
 Minimum sample percentage: 0.1
 Minimum average coverage depth: 2
Number of Unique stacks (before filter):0
Minimum Samples: 0
Minimum Average Coverage: 2
Number of Unique stacks (after filter):0
Segmentation fault

[config.log](https://github.com/beiko-lab/RADProc/files/2611370/config.log)

I'm assuming there is a failure somewhere in the build due to missing headers but am struggling to find the cause, any ideas?

Many thanks,
Alex

**Comment by praveennr** [comment]
Hi,

Sorry Alex, I somehow missed to see the  open issue. 

Tom,  RADProc couldn't read your input files. I can see you have specified file type as gzfasta and supplying gzfastq files. Can you please change it and try ?

**Comment by Vierod** [comment]
Hi Praveen,

No problem at all. It's been a while since we were trying to run this, will give it another go soon and see if we manage.

Alex
