### ISSUE TITLE
Working with other types of data ?

### ISSUE THREAD

**Issue by BiodivGenomic** [beiko-lab/RADProc#4]
Hello, not really an issue...
I would like to use RADProc with data from an other Reduced-Representation-Library method.
Can RADProc be used with data without the restriction-enzyme pattern ?
Thanks in advance

**Comment by praveennr** [comment]
Hi,
Interesting question, I haven't tried it before. But, RADProc should work as long as the input is short reads and in any of the accepted input file formats. 

~Praveen
