### ISSUE TITLE
naming suggestion

### ISSUE THREAD

**Issue by thierrygosselin** [beiko-lab/RADProc#8]
Hey Praveen, me again.
1 suggestion I have for the file naming inside RADProc. 
You use the full filename to name your output _à la ustacks_ namely: `sample.name.fq.alleles.tsv`
may I suggest, for future update, to trim the `fq` out of it, to really keep `sample.name`. Project info file, population map, etc don't have to be modified to include the `fq` into the name and the id remains the same as the wetlab vials (e.g.)...

Cheers
Thierry

**Comment by praveennr** [comment]
Hey Thierry,
Currently RADProc should be trimming the trailing "fq" as long as it is the last part in the input filename i.e., "samplename.fq". Not sure why do you see them in the output filenames, can you share a sample input filename?

~Praveen

**Comment by thierrygosselin** [comment]
I have gz files...
e.g. `TSU-DOC-ADU-2019-001.fq.gz`

I understand why now.
